name: CI/CD
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check:
    name: Flake check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Nix installer
        uses: DeterminateSystems/nix-installer-action@v14

      - name: Nix flake check
        run: nix flake check
